[phases.setup]
nixPkgs = ["nodejs"]

[phases.install]
cmds = [
  "npm install",
  "cd packages/prisma && npx prisma generate --schema=prisma/schema.prisma",
  "cd ../../apps/api && npm install"
]

[phases.build]
cmds = [
  "cd apps/api && npm run build"
]

[start]
cmd = "cd apps/api && npm start" 