[phases.setup]
nixPkgs = ["nodejs"]

[phases.install]
cmds = [
  "chmod +x railway-build-api.sh",
  "./railway-build-api.sh"
]

[phases.build]
cmds = [
  "echo 'Build completed in install phase'"
]

[start]
cmd = "cd apps/api && npm start" 