[phases.setup]
nixPkgs = ["nodejs"]

[phases.install]
cmds = [
  "npm install",
  "cd packages/prisma && npx prisma generate --schema=prisma/schema.prisma"
]

[phases.build]
cmds = [
  "cd apps/api && ln -sf ../../node_modules node_modules && npm run build"
]

[start]
cmd = "cd apps/api && npm start" 