[build]
builder = "nixpacks"

[deploy]
startCommand = "cd apps/api && npm start"
healthcheckPath = "/health"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[build.steps]
install = "pnpm install --frozen-lockfile"
build = "cd packages/prisma && npx prisma generate --schema=prisma/schema.prisma && cd ../../apps/api && npm run build" 